DOC-8576 Update CSS for group-nav as per design
couchbase/docs-ui pull request #111
Opened 2021-06-14 21:09 UTC by amarantha-k

Update background color component group-title and version selector

2021-06-14 22:13 UTC, mojavelinux requested changes

2021-06-14 22:13 UTC, mojavelinux commented on src/css/nav.css
> +  background: url(data:image/svg+xml;charset=US-ASCII,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20448%20512%22%3E%3Cpath%20fill%3D%22%23333%22%20d%3D%22M207.029
If we remove the linear gradient from this select element, we should remove it from the one in the search results as well. In other words, they should match.

2021-06-14 22:13 UTC, mojavelinux commented on src/css/nav.css
> +  text-transform: uppercase;
This line has a trailing space.

2021-06-15 14:19 UTC, amarantha-k commented
Incorporated feedback from @mojavelinux

2021-06-15 19:32 UTC, mojavelinux approved these changes

2021-06-16 08:01 UTC, merged