Rayoffiah/adding stem support
couchbase/docs-ui pull request #127
Opened 2021-11-12 15:06 UTC by RayOffiah

Adding STEM support to the site.

Not working at the moment; does not appear to be seeing asciidoc.stem setting.

2021-11-12 19:41 UTC, mojavelinux commented
The preview doesn't provide a full Antora environment. Much of the UI model, and the helpers in particular, are mocked. Therefore, it's not going to provide the depth of metadata needed for this check. But it will work if you try it on a real site.

See https://github.com/couchbase/docs-ui/blob/master/gulp.d/tasks/build-preview-pages.js#L313-L315

2021-11-12 19:42 UTC, mojavelinux requested changes

2021-11-12 19:42 UTC, mojavelinux commented on src/partials/footer-scripts.hbs
> +
Remove this empty line.

2021-11-12 19:42 UTC, mojavelinux commented on src/partials/footer-scripts.hbs
> +    {{#unless (eq ./asciidoc.attributes.stem undefined)}}
The convention we've been following is to not indent logic tags. It creates superfluous nesting in the resulting HTML.

2021-11-12 19:42 UTC, mojavelinux commented on src/partials/footer-scripts.hbs
> +        <script type="text/x-mathjax-config">
The convention we've been following is to not indent top-level tags in a template, such as `<script>`.

2021-11-14 08:53 UTC, mojavelinux approved these changes

2021-11-15 09:36 UTC, maria-robobug approved these changes
👍

2021-11-15 09:52 UTC, mojavelinux commented
FYI, you can obtain the UI bundle from a deploy preview in any Antora environment by appending `dist/ui-bundle.zip` to the deploy preview URL. For example:

https://deploy-preview-127--cb-docs-ui.netlify.app/dist/ui-bundle.zip

You can either set that value in the playbook or pass it to Antora using the `--ui-bundle-url` CLI option.

This allows you to test a change to the UI with the real content before merging into the mainline.

2021-11-15 10:04 UTC, RayOffiah commented
I didn’t think of the command line option. Thanks; I’ll remember that one.

From: Dan Allen ***@***.***>
Date: Monday, 15 November 2021 at 09:52
To: couchbase/docs-ui ***@***.***>
Cc: Ray Offiah ***@***.***>, Author ***@***.***>
Subject: Re: [couchbase/docs-ui] Rayoffiah/adding stem support (PR #127)

FYI, you can obtain the UI bundle from a deploy preview in any Antora environment by appending dist/ui-bundle.zip to the deploy preview URL. For example:

https://deploy-preview-127--cb-docs-ui.netlify.app/dist/ui-bundle.zip

You can either set that value in the playbook or pass it to Antora using the --ui-bundle-url CLI option.

This allows you to test a change to the UI with the real content before merging into the mainline.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/couchbase/docs-ui/pull/127#issuecomment-968717172>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ASL3EZZX5VZJJFMYBEWGZE3UMDJ67ANCNFSM5H5BOENQ>.

2021-12-17 08:50 UTC, merged